const mockTeams = [
  {
    position: 1,
    club: { name: 'Lixa', stared: true },
    played: 38,
    points: 100,
    gs: 100,
    gc: 30,
    won: 30,
    drawn: 10,
    lost: 0,
  },
  {
    position: 2,
    club: { name: 'Man City', stared: false },
    played: 38,
    points: 86,
    gs: 90,
    gc: 30,
    won: 26,
    drawn: 8,
    lost: 4,
  },
  {
    position: 3,
    club: { name: 'Chelsea', stared: false },
    played: 38,
    points: 90,
    gs: 80,
    gc: 30,
    won: 28,
    drawn: 6,
    lost: 4,
  },
  {
    position: 4,
    club: { name: 'Vizela', stared: false },
    played: 38,
    points: 80,
    gs: 70,
    gc: 30,
    won: 20,
    drawn: 10,
    lost: 8,
  },
  {
    position: 5,
    club: { name: 'V. Santarem', stared: false },
    played: 38,
    points: 70,
    gs: 60,
    gc: 30,
    won: 18,
    drawn: 10,
    lost: 10,
  },
  {
    position: 6,
    club: { name: 'Porto', stared: false },
    played: 38,
    points: 67,
    gs: 58,
    gc: 40,
    won: 19,
    drawn: 10,
    lost: 9,
  },
  {
    position: 7,
    club: { name: 'Benfica', stared: false },
    played: 38,
    points: 65,
    gs: 55,
    gc: 45,
    won: 18,
    drawn: 11,
    lost: 9,
  },
  {
    position: 8,
    club: { name: 'Sporting CP', stared: false },
    played: 38,
    points: 64,
    gs: 50,
    gc: 40,
    won: 18,
    drawn: 10,
    lost: 10,
  },
  {
    position: 9,
    club: { name: 'Braga', stared: false },
    played: 38,
    points: 62,
    gs: 48,
    gc: 44,
    won: 17,
    drawn: 11,
    lost: 10,
  },
  {
    position: 10,
    club: { name: 'Marítimo', stared: false },
    played: 38,
    points: 60,
    gs: 45,
    gc: 42,
    won: 16,
    drawn: 12,
    lost: 10,
  },
  {
    position: 11,
    club: { name: 'Famalicão', stared: false },
    played: 38,
    points: 57,
    gs: 40,
    gc: 50,
    won: 15,
    drawn: 12,
    lost: 11,
  },
  {
    position: 12,
    club: { name: 'Guimarães', stared: false },
    played: 38,
    points: 55,
    gs: 39,
    gc: 49,
    won: 15,
    drawn: 10,
    lost: 13,
  },
  {
    position: 13,
    club: { name: 'Boavista', stared: false },
    played: 38,
    points: 50,
    gs: 35,
    gc: 53,
    won: 13,
    drawn: 11,
    lost: 14,
  },
  {
    position: 14,
    club: { name: 'Gil Vicente', stared: false },
    played: 38,
    points: 48,
    gs: 33,
    gc: 51,
    won: 13,
    drawn: 9,
    lost: 16,
  },
  {
    position: 15,
    club: { name: 'Rio Ave', stared: false },
    played: 38,
    points: 45,
    gs: 31,
    gc: 54,
    won: 12,
    drawn: 9,
    lost: 17,
  },
  {
    position: 16,
    club: { name: 'Estoril', stared: false },
    played: 38,
    points: 42,
    gs: 29,
    gc: 58,
    won: 11,
    drawn: 9,
    lost: 18,
  },
  {
    position: 17,
    club: { name: 'Paços de Ferreira', stared: false },
    played: 38,
    points: 40,
    gs: 28,
    gc: 60,
    won: 10,
    drawn: 10,
    lost: 18,
  },
  {
    position: 18,
    club: { name: 'Arouca', stared: false },
    played: 38,
    points: 35,
    gs: 25,
    gc: 65,
    won: 9,
    drawn: 8,
    lost: 21,
  },
  {
    position: 19,
    club: { name: 'Chaves', stared: false },
    played: 38,
    points: 30,
    gs: 20,
    gc: 70,
    won: 7,
    drawn: 9,
    lost: 22,
  },
  {
    position: 20,
    club: { name: 'Académica', stared: false },
    played: 38,
    points: 25,
    gs: 18,
    gc: 75,
    won: 6,
    drawn: 7,
    lost: 25,
  },
];

export default mockTeams;
