CREATE DATABASE IF NOT EXISTS `${USERS_DATABASE}`;
USE `${USERS_DATABASE}`;
CREATE USER IF NOT EXISTS '${USERS_USER}'@'%' IDENTIFIED BY '${USERS_PASSWORD}';
GRANT ALL PRIVILEGES ON `${USERS_DATABASE}`.* TO '${USERS_USER}'@'%';
FLUSH PRIVILEGES;