version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./frontend/game-sense/dist:/usr/share/nginx/html
      - ./frontend/game-sense/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - club-service
      - live-game-service
      - player-service
      - league-service
      - kafka
    networks:
      - app-network

  club-service:
    build:
      context: backend/club_service
    image: club_service-image
    networks:
      - app-network

  live-game-service:
    build:
      context: backend/live_game_service
    image: live_game_service-image
    networks:
      - app-network
    depends_on:
      - kafka

  player-service:
    build:
      context: backend/player_service
    image: player_service-image
    networks:
      - app-network

  league-service:
    build:
      context: backend/league_service
    image: league_service-image
    networks:
      - app-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - app-network

  kafka:
    image: confluentinc/cp-kafka:7.4.4
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
