version: '3.8'

services:
  club_service:
    image: club_service-image
    build:
      context: club_service
    ports:
      - "${CLUB_SERVICE_PORT}:8080"
    networks:
      - app-network
    env_file:
      - .env

  live_game_service:
    image: live_game_service-image
    build:
      context: live_game_service
    ports:
      - "${LIVE_GAME_SERVICE_PORT}:8080"
    networks:
      - app-network
    env_file:
      - .env

  player_service:
    image: player_service-image
    build:
      context: player_service
    ports:
      - "${PLAYER_SERVICE_PORT}:8080"
    networks:
      - app-network
    env_file:
      - .env

  league_service:
    image: league_service-image
    build:
      context: league_service
    ports:
      - "${LEAGUE_SERVICE_PORT}:8080"
    networks:
      - app-network
    env_file:
      - .env

networks:
  app-network:
    driver: bridge
