services:
  club_service:
    image: club_service-image
    build:
      context: backend/club_service
    ports:
      - "${CLUB_SERVICE_PORT}:${INTERNAL_SPRING_PORT}"
    networks:
      - app-network
    env_file:
      - .env

  live_game_service:
    image: live_game_service-image
    build:
      context: backend/live_game_service
    ports:
      - "${LIVE_GAME_SERVICE_PORT}:${INTERNAL_SPRING_PORT}"
    networks:
      - app-network
    env_file:
      - .env

  player_service:
    image: player_service-image
    build:
      context: backend/player_service
    ports:
      - "${PLAYER_SERVICE_PORT}:${INTERNAL_SPRING_PORT}"
    networks:
      - app-network
    env_file:
      - .env

  league_service:
    image: league_service-image
    build:
      context: backend/league_service
    ports:
      - "${LEAGUE_SERVICE_PORT}:${INTERNAL_SPRING_PORT}"
    networks:
      - app-network
    env_file:
      - .env

  frontend:
    image: frontend-image
    build:
      context: frontend/game-sense
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_INTERNAL_PORT}"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
