version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./frontend/game-sense/dist:/usr/share/nginx/html
      - ./frontend/game-sense/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - club-service
      - live-game-service
      - player-service
      - league-service
    networks:
      - app-network

  club-service:
    build:
      context: backend/club_service
    image: club_service-image
    networks:
      - app-network

  live-game-service:
    build:
      context: backend/live_game_service
    image: live_game_service-image
    networks:
      - app-network

  player-service:
    build:
      context: backend/player_service
    image: player_service-image
    networks:
      - app-network

  league-service:
    build:
      context: backend/league_service
    image: league_service-image
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
